// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/v1/job.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_CREATED     JobState = 1 // Job configured and resources allocated successfully.
	JobState_JOB_STATE_STARTING    JobState = 2 // Job is starting.
	JobState_JOB_STATE_STARTED     JobState = 3 // Job has started.
	JobState_JOB_STATE_STOPPING    JobState = 4 // Job is stopping.
	JobState_JOB_STATE_STOPPED     JobState = 5 // Job has stopped.
	JobState_JOB_STATE_FAILED      JobState = 6 // Failure as a result of the service, rather than the underlying Job process.
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_CREATED",
		2: "JOB_STATE_STARTING",
		3: "JOB_STATE_STARTED",
		4: "JOB_STATE_STOPPING",
		5: "JOB_STATE_STOPPED",
		6: "JOB_STATE_FAILED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_CREATED":     1,
		"JOB_STATE_STARTING":    2,
		"JOB_STATE_STARTED":     3,
		"JOB_STATE_STOPPING":    4,
		"JOB_STATE_STOPPED":     5,
		"JOB_STATE_FAILED":      6,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_job_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_api_v1_job_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{0}
}

type RunJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       string                 `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"` // Program to run as a job.
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`       // Arguments to pass to the program.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobRequest) Reset() {
	*x = RunJobRequest{}
	mi := &file_api_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobRequest) ProtoMessage() {}

func (x *RunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobRequest.ProtoReflect.Descriptor instead.
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *RunJobRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *RunJobRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type RunJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the started job.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobResponse) Reset() {
	*x = RunJobResponse{}
	mi := &file_api_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobResponse) ProtoMessage() {}

func (x *RunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobResponse.ProtoReflect.Descriptor instead.
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *RunJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the job to stop.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobRequest) Reset() {
	*x = StopJobRequest{}
	mi := &file_api_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobRequest) ProtoMessage() {}

func (x *StopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobRequest.ProtoReflect.Descriptor instead.
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *StopJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobResponse) Reset() {
	*x = StopJobResponse{}
	mi := &file_api_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobResponse) ProtoMessage() {}

func (x *StopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobResponse.ProtoReflect.Descriptor instead.
func (*StopJobResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{3}
}

type QueryJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the job to query.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJobRequest) Reset() {
	*x = QueryJobRequest{}
	mi := &file_api_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJobRequest) ProtoMessage() {}

func (x *QueryJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJobRequest.ProtoReflect.Descriptor instead.
func (*QueryJobRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *QueryJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         JobState               `protobuf:"varint,1,opt,name=state,proto3,enum=job.v1.JobState" json:"state,omitempty"`  // State of the job.
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // Exit code of the job.
	Signal        string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`                      // Signal received by the process.
	Interrupted   bool                   `protobuf:"varint,4,opt,name=interrupted,proto3" json:"interrupted,omitempty"`           // Set to `true` stopped by user.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJobResponse) Reset() {
	*x = QueryJobResponse{}
	mi := &file_api_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJobResponse) ProtoMessage() {}

func (x *QueryJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJobResponse.ProtoReflect.Descriptor instead.
func (*QueryJobResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *QueryJobResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *QueryJobResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *QueryJobResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *QueryJobResponse) GetInterrupted() bool {
	if x != nil {
		return x.Interrupted
	}
	return false
}

type StreamJobOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the job to stream output from.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobOutputRequest) Reset() {
	*x = StreamJobOutputRequest{}
	mi := &file_api_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobOutputRequest) ProtoMessage() {}

func (x *StreamJobOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamJobOutputRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *StreamJobOutputRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StreamJobOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // Streamed bytes from the jobs output.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobOutputResponse) Reset() {
	*x = StreamJobOutputResponse{}
	mi := &file_api_v1_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobOutputResponse) ProtoMessage() {}

func (x *StreamJobOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobOutputResponse.ProtoReflect.Descriptor instead.
func (*StreamJobOutputResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *StreamJobOutputResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_api_v1_job_proto protoreflect.FileDescriptor

const file_api_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/job.proto\x12\x06job.v1\"=\n" +
	"\rRunJobRequest\x12\x18\n" +
	"\aprogram\x18\x01 \x01(\tR\aprogram\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\" \n" +
	"\x0eRunJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eStopJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fStopJobResponse\"!\n" +
	"\x0fQueryJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x91\x01\n" +
	"\x10QueryJobResponse\x12&\n" +
	"\x05state\x18\x01 \x01(\x0e2\x10.job.v1.JobStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\x12 \n" +
	"\vinterrupted\x18\x04 \x01(\bR\vinterrupted\"(\n" +
	"\x16StreamJobOutputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x17StreamJobOutputResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output*\xb0\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_CREATED\x10\x01\x12\x16\n" +
	"\x12JOB_STATE_STARTING\x10\x02\x12\x15\n" +
	"\x11JOB_STATE_STARTED\x10\x03\x12\x16\n" +
	"\x12JOB_STATE_STOPPING\x10\x04\x12\x15\n" +
	"\x11JOB_STATE_STOPPED\x10\x05\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x062\x96\x02\n" +
	"\n" +
	"JobService\x127\n" +
	"\x06RunJob\x12\x15.job.v1.RunJobRequest\x1a\x16.job.v1.RunJobResponse\x12:\n" +
	"\aStopJob\x12\x16.job.v1.StopJobRequest\x1a\x17.job.v1.StopJobResponse\x12=\n" +
	"\bQueryJob\x12\x17.job.v1.QueryJobRequest\x1a\x18.job.v1.QueryJobResponse\x12T\n" +
	"\x0fStreamJobOutput\x12\x1e.job.v1.StreamJobOutputRequest\x1a\x1f.job.v1.StreamJobOutputResponse0\x01B*Z(github.com/nixpig/jobworker/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_job_proto_rawDescOnce sync.Once
	file_api_v1_job_proto_rawDescData []byte
)

func file_api_v1_job_proto_rawDescGZIP() []byte {
	file_api_v1_job_proto_rawDescOnce.Do(func() {
		file_api_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_job_proto_rawDesc), len(file_api_v1_job_proto_rawDesc)))
	})
	return file_api_v1_job_proto_rawDescData
}

var file_api_v1_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_job_proto_goTypes = []any{
	(JobState)(0),                   // 0: job.v1.JobState
	(*RunJobRequest)(nil),           // 1: job.v1.RunJobRequest
	(*RunJobResponse)(nil),          // 2: job.v1.RunJobResponse
	(*StopJobRequest)(nil),          // 3: job.v1.StopJobRequest
	(*StopJobResponse)(nil),         // 4: job.v1.StopJobResponse
	(*QueryJobRequest)(nil),         // 5: job.v1.QueryJobRequest
	(*QueryJobResponse)(nil),        // 6: job.v1.QueryJobResponse
	(*StreamJobOutputRequest)(nil),  // 7: job.v1.StreamJobOutputRequest
	(*StreamJobOutputResponse)(nil), // 8: job.v1.StreamJobOutputResponse
}
var file_api_v1_job_proto_depIdxs = []int32{
	0, // 0: job.v1.QueryJobResponse.state:type_name -> job.v1.JobState
	1, // 1: job.v1.JobService.RunJob:input_type -> job.v1.RunJobRequest
	3, // 2: job.v1.JobService.StopJob:input_type -> job.v1.StopJobRequest
	5, // 3: job.v1.JobService.QueryJob:input_type -> job.v1.QueryJobRequest
	7, // 4: job.v1.JobService.StreamJobOutput:input_type -> job.v1.StreamJobOutputRequest
	2, // 5: job.v1.JobService.RunJob:output_type -> job.v1.RunJobResponse
	4, // 6: job.v1.JobService.StopJob:output_type -> job.v1.StopJobResponse
	6, // 7: job.v1.JobService.QueryJob:output_type -> job.v1.QueryJobResponse
	8, // 8: job.v1.JobService.StreamJobOutput:output_type -> job.v1.StreamJobOutputResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_job_proto_init() }
func file_api_v1_job_proto_init() {
	if File_api_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_job_proto_rawDesc), len(file_api_v1_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_job_proto_goTypes,
		DependencyIndexes: file_api_v1_job_proto_depIdxs,
		EnumInfos:         file_api_v1_job_proto_enumTypes,
		MessageInfos:      file_api_v1_job_proto_msgTypes,
	}.Build()
	File_api_v1_job_proto = out.File
	file_api_v1_job_proto_goTypes = nil
	file_api_v1_job_proto_depIdxs = nil
}
